Repository Baezon/pof-tools, pull requests merged in 2022-09, with the labels that each got.

#71 uvec/fvec visualization
  pof/src/types.rs
  src/main.rs
  src/primitives.rs
  src/ui.rs
  src/ui_properties_panel.rs
Labels: enhancement

#95 Add support for translation axis/type
  pof/src/parse.rs
  pof/src/types.rs
  pof/src/write.rs
  src/ui.rs
  src/ui_properties_panel.rs
Labels: enhancement

#96 Properly display destroyed models
  pof/src/types.rs
  src/main.rs
  src/ui.rs
  src/ui_properties_panel.rs
Labels: enhancement, fix

#97 Fix a crash when modifying turrets
  src/ui_properties_panel.rs
Labels: fix

#100 Add orthographic and other camera views
  src/main.rs
  src/ui.rs
Labels: enhancement

#101 Fix subobj name duplication detection
  pof/src/types.rs
  src/ui.rs
Labels: fix
