Repository Baezon/pof-tools, pull requests merged in 2022-04, with the labels that each got.

#42 Handle large vert/norm counts
  pof/src/parse.rs
  pof/src/types.rs
  pof/src/write.rs
  src/ui.rs
  src/ui_properties_panel.rs
Labels: enhancement

#47 add pof-census tool
  tools/pof-census/.gitignore
  tools/pof-census/Cargo.lock
  tools/pof-census/Cargo.toml
  tools/pof-census/src/main.rs
  tools/pof-census/src/vp.rs
Labels: enhancement

#46 Introduce new properties handling
  pof/src/types.rs
  src/main.rs
  src/ui.rs
  src/ui_properties_panel.rs
Labels: enhancement

#50 Allow for moving only the offset of a subobject
  pof/src/types.rs
  pof/src/write.rs
  src/main.rs
  src/ui.rs
  src/ui_properties_panel.rs
Labels: enhancement, fix

#51 Add some new info display
  src/ui.rs
  src/ui_properties_panel.rs
Labels: enhancement

#49 feat: don't triangulate wireframe
  src/main.rs
  src/ui.rs
Labels: enhancement, clean up

#55 Fix panic display
  src/main.rs
Labels: fix

#56 Make shaders more permissive
  pof/src/parse.rs
  pof/src/types.rs
  src/main.rs
Labels: fix

#59 Fix dae import/export UVs
  pof/src/parse.rs
  pof/src/write.rs
Labels: fix

#61 default Dock should be orthogonal
  pof/src/types.rs
Labels: fix

#57 more prehistory, simplify recalculate_bboxes
  pof/src/parse.rs
  pof/src/types.rs
  pof/src/write.rs
Labels: enhancement

#62 write glow points
  pof/src/write.rs
Labels: fix

#63 remove Polygon.center and calculate it on the fly
  pof/src/parse.rs
  pof/src/types.rs
  pof/src/write.rs
  src/main.rs
Labels: clean up

#67 Write/Read new pof version
  Cargo.lock
  pof/src/parse.rs
  pof/src/types.rs
  pof/src/write.rs
  src/main.rs
  src/ui.rs
Labels: enhancement

#68 Add some warnings and only sanitize empty bbox
  pof/src/types.rs
  src/ui.rs
  src/ui_properties_panel.rs
Labels: enhancement

#69 Strip '-material' on gltf parse, and dont add it on write
  pof/src/parse.rs
  pof/src/write.rs
Labels: fix
